name: Notify Stale PR


on:
  schedule:
    - cron: '*/5 * * * *'


jobs:
  notify:
    name: Test Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Echo Something
        run: echo "Sending notification..."

